import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import prettier from 'eslint-config-prettier'

/**
 * Flat config, `.mjs` because the package is CommonJS and a bare
 * `eslint.config.js` would be read as such.
 *
 * The rule set is deliberately small. It was chosen from what the source
 * already assumes is being enforced: fourteen `eslint-disable` comments were
 * written here before any linter existed — eleven for `exhaustive-deps` and
 * three for `no-console` — and a suppression for a rule that never runs is a
 * comment, not a decision. These are the rules that make those comments mean
 * something again.
 */
export default tseslint.config(
  {
    /**
     * A suppression that has stopped suppressing anything is worse than no
     * suppression: it claims a problem exists where there is none, and three of
     * them had accumulated here before the linter first ran. Fatal, so they are
     * deleted when they expire rather than a decade later.
     */
    linterOptions: { reportUnusedDisableDirectives: 'error' }
  },
  {
    // Build output, dependencies, and the Windows helper sources that are
    // generated by `build:shadowhost` rather than written.
    ignores: ['out/**', 'dist/**', 'node_modules/**', 'resources/**', '**/*.tsbuildinfo']
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    /*
     * Build-time scripts: plain CommonJS run by `node`, not by Electron and not
     * through the bundler, so `require` and the Node globals are the point
     * rather than a mistake. They stay in this project's tree — and therefore
     * under this project's linter — because they enforce its own rules; see
     * `scripts/verify-release.cjs`.
     */
    files: ['scripts/**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        require: 'readonly',
        module: 'writable',
        process: 'readonly',
        __dirname: 'readonly'
      }
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off'
    }
  },

  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    rules: {
      // TypeScript resolves every identifier already, and this rule would
      // otherwise need a second list of DOM and Node globals kept in step
      // with the three tsconfigs.
      'no-undef': 'off',

      // The tsconfigs already fail on an unused local. This adds the argument
      // case, with the underscore escape hatch that ssh2 and Electron callback
      // signatures need — `(_event, payload) => …` is not a mistake.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
      ],

      // The three `trace()` helpers in src/main/rdp opt out by hand and are
      // gated behind TERMINALDECK_RDP_TRACE. Nothing else should log to a
      // console the packaged app has no window onto; a real problem belongs in
      // console.error, which stays allowed.
      'no-console': ['error', { allow: ['warn', 'error'] }]
    }
  },

  {
    files: ['src/renderer/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      // No false positives and a genuine bug class: a hook behind a condition
      // silently corrupts the hook order for every later render.
      'react-hooks/rules-of-hooks': 'error',

      // An error, now that its output has been read. The first run found a stale
      // dependency that had been silently freezing a pinned desktop's size, and
      // three suppressions that were suppressing nothing at all. The ten that
      // remain each say in a comment why they are there — which is the bar for
      // adding another.
      'react-hooks/exhaustive-deps': 'error'
    }
  },

  // Last, so it wins: formatting is Prettier's job, and every rule that would
  // argue with it is switched off rather than fought.
  prettier
)
